### PR TITLE
float vs decimal

### PR DESCRIPTION
**Pull request by IstvanSafar**
For invoicing systems I would suggest to use decimal instead of float.  Everything else looks good.

### CODE REVIEW

**Comment by agabor** [comment]
Yes, that makes sense, but your branch does not compile. Could you please fix the compilation errors?

**Comment by IstvanSafar** [comment]
okay, I added a new function in xml parser. I hope it will work, i haven't tried , I modified online

**Comment by IstvanSafar** [comment]
Reposnses left from the model. Sorry about it, now I downloaded the code and I built it.

**Comment by IstvanSafar** [comment]
Auth error in test.
<sikeres xmlns="http://www.szamlazz.hu/xmlszamlavalasz">false</sikeres><hibakod xmlns="http://www.szamlazz.hu/xmlszamlavalasz"><![CDATA[3]]></hibakod><hibauzenet xmlns="http://www.szamlazz.hu/xmlszamlavalasz"><![CDATA[Sikertelen bejelentkezés.]]></hibauzenet>

**Comment by IstvanSafar** [comment]
```xml
<sikeres xmlns="http://www.szamlazz.hu/xmlszamlavalasz">false</sikeres><hibakod xmlns="http://www.szamlazz.hu/xmlszamlavalasz"><![CDATA[3]]></hibakod><hibauzenet xmlns="http://www.szamlazz.hu/xmlszamlavalasz"><![CDATA[Sikertelen bejelentkezés.]]></hibauzenet>
@agabor

**Comment by IstvanSafar** [comment]
https://github.com/codesharp-hu/szamlazz-hu-sdk/pull/5#issuecomment-933646132

failed because wrong auth:
 ```xml
<sikeres xmlns="http://www.szamlazz.hu/xmlszamlavalasz">false</sikeres><hibakod xmlns="http://www.szamlazz.hu/xmlszamlavalasz"><![CDATA[3]]></hibakod><hibauzenet xmlns="http://www.szamlazz.hu/xmlszamlavalasz"><![CDATA[Sikertelen bejelentkezés.]]></hibauzenet>
@agabor

**Comment by agabor** [comment]
Yes, you need an API key to run the tests. But otherwise, it now looks fine, I am merging this. Thank you for your contribution!

**Pull request merged**
